ci(release): fix release on tag and main

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -2,8 +2,6 @@ name: Build and Release
 
 on:
   push:
-    branches:
-      - main
     tags:
       - 'v*.*.*'
 
@@ -15,6 +13,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Check if tag is on main branch
+        run: |
+          git fetch origin main
+          if ! git branch -r --contains ${{ github.sha }} | grep -q 'origin/main'; then
+            echo "Tag is not on a commit in the main branch history. Aborting."
+            exit 1
+          fi
       - name: Build C++ library
         run: make
       - name: Upload Linux artifact
@@ -27,6 +32,13 @@ jobs:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Check if tag is on main branch
+        run: |
+          git fetch origin main
+          if ! git branch -r --contains ${{ github.sha }} | grep -q 'origin/main'; then
+            echo "Tag is not on a commit in the main branch history. Aborting."
+            exit 1
+          fi
       - name: Build C++ library
         run: make
       - name: Upload macOS artifact
@@ -39,6 +51,13 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Check if tag is on main branch
+        run: |
+          git fetch origin main
+          if ! git branch -r --contains ${{ github.sha }} | grep -q 'origin/main'; then
+            echo "Tag is not on a commit in the main branch history. Aborting."
+            exit 1
+          fi
       - name: Build C++ library
         run: .\makefile.bat
       - name: Upload Windows artifact
@@ -86,7 +105,6 @@ jobs:
         run: python -m build
 
       - name: Create Release
-        if: startsWith(github.ref, 'refs/tags/')
         uses: softprops/action-gh-release@v1
         with:
           files: |
